
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    restart: always
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
