// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqqimyxftnszqzevwmdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcWlteXhmdG5zenF6ZXZ3bWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTU5NTMsImV4cCI6MjA1ODg3MTk1M30.MlUyjQ789YZOveHyBH_iE-Blvtwdx19rsPccp6pR54M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);